### ISSUE TITLE
Output frequency issue?

### ISSUE THREAD

**Issue by NinavonReich** [F5OEO/rpitx#148]
Hi there, thanks for your great work!
Actually I am testing but have no success. :(

I want to use pocsag at 184.35 MHz and 512 baud and had edited the testpocsag.sh:
```
#!/bin/sh

printf "0813589A:TEST" | sudo ./pocsag -f "184350000" -r 512
```

In putty im running the script with:
pi@pi:~/rpitx $ sudo ./testpocsag.sh

With the following output:
Channel 14 CBSize 24006 UsermemSize 12003
Using mbox device /dev/vcio.
816204 Size NUM PAGES 200 PAGE_SIZE 4096
BufferSize 12003 , cb 24006 user 12003
Found PLL solution for frequency 184.3MHz : divider:9 VCO: 1659.1MHz
Master PLLC Locked
PCM prediv = 239
PCM clk=4086 / 145

Seems to work, but only on a false frequency...
Why do I have this "issue" and how do I fix it?

ty :>

**Comment by pyrog** [comment]
Why do you think it work but only on a **false frequency** ?

Because it display `Found PLL solution for frequency 184.3MHz` and your frequency should be 184.350 MHz ?
In this case, this is just a rounding from [F5OEO/librpitx gpio.cpp#L269](https://github.com/F5OEO/librpitx/blob/master/src/gpio.cpp#L269)

**Comment by F5OEO** [comment]
Display frequency is rounded but output frequency is OK.
