### ISSUE TITLE
Rpitx keeps crashing my PI

### ISSUE THREAD

**Issue by Slayingripper** [F5OEO/rpitx#165]
first time i run Rpitx it was working fine but after a 2nd restart it started freezing the pi making me have to force restart it .

**Comment by phantomdennis** [comment]
I am having the same issue. The PI 2B is crashing as soon as I start transmitting.

**Comment by NicholasBlackburn1** [comment]
did you try reinstalling the rpitx software

**Comment by phantomdennis** [comment]
I removed it and cloned the git again and the same result. Is there something special I need to do to remove the installation beyond removing the directory?

**Comment by gr01d** [comment]
Mine crashes after transmitting POCSAG, can you play some music with mplayer then use rpitx. Mine says "Audio device got stuck" and I am unable to play music until I rebooted the Pi.

**Comment by Hysteria1212** [comment]
Hi,

did you overclock your raspi? I had this problem with my raspberry pi 1
when using the maximum cpu clock.

Am Mo., 29. Apr. 2019 um 22:58 Uhr schrieb gr01d <notifications@github.com>:

**Comment by phantomdennis** [comment]
I do not overclock my pi. It says 250Mhz when the rpitx finishes installing. I did re-install. I am ran these tests both over SSH (which disconnects when the transmissions start) and from the terminal infront of the device. I reboot between tests and found this:

~/rpitx$ ./easytune.sh

I leave the default frequency: 434.0
**Tune** - Screen immediately turns off and the system fails - the signal stays up at a low power until the pi is turned off
**Chirp** - Screen immediately turns off and the system fails - the signal pops up and starts to move for about 2 seconds then stops and the signal stays at one frequency with low power until the pi is rebooted.
**Spectrum** - Nothing happens - The system fails and nothing is transmitted.
**RfMyFace** - I did not try this, I do not have a camera installed.
**FMRDS** - Screen immediately turns off and the system fails - the signal pops up lasts about 3 seconds then turns off.
**NFM** - Screen immediately turns off and the system fails - the signal pops up and stays up until the pi is rebooted. When spanned all the way in on the signal there is frequency modulation. But when tuned on the radio it sounds like a demon breathing.
**SSB** - Screen immediately turns off and the system fails - Then a small signal pops up. I cannot demod SSB at the moment but there is a signal. 

~$./rpitx/easytune.sh - The menus pop up, I press transmit, it says transmitting, but there is no RF. IT does not fail, the pi does not reboot.

**Comment by dachshund-digital** [comment]
Same for me buster and RPiTex and buster combo, kills my Pi ZeroW.

**Comment by gr01d** [comment]
Mine works now, it is Rpi 3B+ with the current buster updated to latest packages. The` /boot/config.txt `has the 
`gpu_freq=250`. The only problem is if you are streaming music with mplayer, the music stops when you use rpitx. Debug log shows audio device got stuck errors. A full reboot will restore the music playing capability of the pi.

**Comment by dachshund-digital** [comment]
I also finally got only an older 3B, not even a 3B+, with buster working randomly... It still fails more often than not.  I am explicitly using sendiq to emulate RF remote signals.  I often have to run the same sendiq command 3 to 10 times, sometimes more, to actually get any transmission broadcast.  Looking at the code a bit, it is not clear where the issue is, because the software does so little error reporting, and has no verbose mode.  Although I have written software in C, I have never do it on Linux, only on Windows and Macintosh OSes.  Walking though the code suggests since the sendiq program is not reporting any errors, it might be the transmit buffer is corrupted, so the signal plays incorrectly, randomly.  Or some error is being encountered that is just never being reported.  I suspect what happens, depends on only on the OS distribution but also the make/model of Pi.

**Comment by Fattcat** [comment]
For me still get freezed whenever I start transmitting freq for example tune or fmrds it just transmit and it freezing my RPi4 model B with 8GB ram memory. And stuck it.

**Comment by Jibun-no-Kage** [comment]
RPiTx was fun while it lasted.  But clearly it is done, either because the newer hardware just does not have the ability to support the idea, or the desire to resolve the issues with it and the Pi 4 are not present.  It has for me only worked so-so on a Pi Zero as well.  Can't get a Pi Zero 2, so can't test that as yet either.

The truth is, RPiTx was taking advantage of a flexibility in the device that was never part of the design.  I finally just got a USB SDR module, and use that for most of what I used RPiTx for.  The only thing that bugs me is that no one seems to want to create a breakout board that explicitly supports 303.875 MHz, which is what a lot of my remotes use.  You can find 433 MHz break out boards all over the place on the net, but not 303.875 MHz.
