### ISSUE TITLE
Question on Useage

### ISSUE THREAD

**Issue by mikenolet** [F5OEO/rpitx#49]
I am trying to capture various RF signals from various household remotes using RTL_SDR for play back using the RPITX software. I am looking to use these signals in a home automation software I am using. I believe I have successfully captured 2 signals as .IQ files and attempted to play them back using RPITX. The signal broadcast as I was able to see it in SDR# but my fan did not turn on as I was hoping. I am not sure if the files need to be converted in any way
I have included links to the files:
Turn fan low: https://drive.google.com/open?id=0B0MQEEqJHGUIcDQtaWpWWEE3OUE
Turn fan off: https://drive.google.com/open?id=0B0MQEEqJHGUIWHlZeTNNNUtpUk0
This is the process I am using:
Run the following command: rtl_sdr -f 303849000 capture.iq and hit the button on the remote. The ceiling fan uses 303.849.000Mhz
Then try to transmith the signal by running this command on the pi: sudo rpitx rpitx -i /home/pi/rpitx/sig/fan_low.iq -f 303849000
Output from rpitx (looks like the wrong frequency is being broadcast)
Warning : Using harmonic 41 memory: 1024 MB processor: Broadcom BCM2836 i2cDevice: /dev/i2c-1 model: Model B Pi 2 manufacturer: Embest pcb revision: 1 warranty void: no revision: a21041 peripheral base: 0x3f000000 Jessie Using mbox device /dev/vcio. 3616000 Size NUM PAGES 883 PAGE_SIZE 4096 MASH 1 Freq PLL# 6 Calibrate : ppm=0 DMA 167ns:1503ns WaitNano=20833 F1=361486188.332892 TuneFrequency 361509780.765417 F2=361518093.5 56929 Initial Resolution(Hz)=31905.224036 ResolutionPWMF 257.300194 NbStep=124 D ELAYStep=9 ****** STARTING TRANSMIT ******** END OF PiTx

**Comment by frq93113** [comment]
Hello,
I don't know if it is the best way to capture an iq signal this way. I think your file it is to big, and contains eroneous data due to aliasing.
I would recommend using gnuradio to do this by creating a capture graph, whith correct filtering.
Then in you graph you can have an ouput sink that writes the iq file.
In gnuradio you will be able as well to demod your signal, I guess yours is OOK (On Off keying, similar to morse).
I played with that a while ago, and I was able to record and decode properly various home devices: Door bell, alarm sensors.
I haven't use rpitx yet to try the replay mode, which I would like to.

If you are new to gnuradio, there are good tutorials on youtube based on hack rf, but the examples can be  adapted easily to an RTLSDR stick.
